# Generated by Django 3.0.7 on 2020-09-28 18:10

from django.db import migrations


def set_project_index(apps, schema_editor):
    Project = apps.get_model('tasks', 'Project')
    for user_id in Project.objects.values_list('user_id', flat=True).order_by().distinct():
        for index, project in enumerate(Project.objects.filter(user_id=user_id), 1):
            project.index = index
            project.save()


def set_task_index(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    for project_id in Task.objects.values_list('project_id', flat=True).order_by().distinct():
        for index, task in enumerate(Task.objects.filter(project_id=project_id), 1):
            task.index = index
            task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200928_2006'),
    ]

    operations = [
        migrations.RunPython(set_project_index),
        migrations.RunPython(set_task_index),
    ]
